var today = new Date();
var day = today.getDate();
console.log(day);
var month = today.getMonth();
console.log(month);
var year = today.getFullYear();
console.log(year);
var time = today.getTime();
console.log(time);
var time2 = today.getHours();
console.log(time2);
var time3 = today.getMinutes();
console.log(time3);
var result = today.toString();
console.log(result);
var oldDay = new Date();
oldDay.setMonth(11);
oldDay.setFullYear(2089);
console.log(oldDay);